name: Node.js CI

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      # Backend
      - name: Install backend deps
        run: npm ci
        working-directory: ./backend

      - name: Build backend
        run: npm run build --if-present
        working-directory: ./backend

      - name: Test backend
        run: npm test
        working-directory: ./backend

      # Frontend
      - name: Install frontend deps
        run: |
          if [ -f package-lock.json ]; then
            npm ci
          else
            npm install
          fi
        working-directory: ./frontend

      - name: Build frontend
        run: npm run build --if-present
        working-directory: ./frontend

      - name: Test frontend
        run: npm test
        working-directory: ./frontend
